---
development:
  cloud_name: dfpqw9ezj
  api_key: "677326917137244"
  api_secret: LYPy1MmMnNoJjltMROi_BQBSbz8
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dfpqw9ezj
  api_key: "677326917137244"
  api_secret: LYPy1MmMnNoJjltMROi_BQBSbz8
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dfpqw9ezj
  api_key: "677326917137244"
  api_secret: LYPy1MmMnNoJjltMROi_BQBSbz8
  enhance_image_tag: true
  static_file_support: false
